### ISSUE TITLE
beforeEach, afterEach, etc not working

### ISSUE THREAD

**Issue by hungps** [pandell/mocha-testdata#15]
```javascript
let users: ITestUser[]

describe("Models", () => {
  describe("User", () => {
    beforeEach((done) => {
      users = SampleData.getUsers()

      done()
    })

    given(users).it("should create the new user with the correct information", ({ current, expect }) => {
      assert.equal(current.id, expect.id)
      assert.equal(current.username, expect.username)
      assert.equal(current.info.username, expect.username)
    })

    given(users).it("should update the user information when call User#updateInfo()", ({ current }) => {
      current.updateInfo({ username: "anotherUsername" })

      assert.equal(current.info.username, "anotherUsername")
      assert.equal(current.username, "anotherUsername")
    })
  })
})
```

The `users` variable is always undefined

**Comment by jgoz** [comment]
Test data has to be available in a static context. `given` will execute when the test suite is _parsed_ and register all of the inner test cases. But at that point, `users` will be undefined, so no test cases will be registered.

Unfortunately there is no way around this with the current design. I would recommend using `users.forEach(current => { ... })` inside of each test.

**Comment by hungps** [comment]
> Test data has to be available in a static context. `given` will execute when the test suite is _parsed_ and register all of the inner test cases. But at that point, `users` will be undefined, so no test cases will be registered.
> 
> Unfortunately there is no way around this with the current design. I would recommend using `users.forEach(current => { ... })` inside of each test.

Thanks
