### ISSUE TITLE
[Solved] Console shows all inputs when reporting test results

### ISSUE THREAD

**Issue by CG-Tespy** [pandell/mocha-testdata#16]
I've been running some tests with complex objects as inputs, and the console window shows all their fields when reporting whether the tests passed or failed. Is there a way to make it so that that doesn't happen?

**Comment by 101100** [comment]
If you add a `description` attribute to those objects, that will be printed instead of the whole object.

That's described in the `README` [here](https://github.com/pandell/mocha-testdata#data).

**Comment by CG-Tespy** [comment]
I added description values to the objects in the tests (before the Arrange phase), and all the fields still show up.

**Comment by CG-Tespy** [comment]
Forgot to mention that the inputs as provided as an array thereof. The array containing the objects is passed to the given() function

**Comment by 101100** [comment]
Can you post your code?

**Comment by CG-Tespy** [comment]
Here you go.

```
given(resources.chapters).it("ConstructorAcceptsCorrectInputs", function(chapter)
{
    chapter.description = chapter.name;
    //...

});
```

**Comment by 101100** [comment]
Ah, that explains it.  What the library does is generate the title for each test _before_ the test is executed.  That is how it adapts the multiple data points into mocha tests which each expect a name before execution.  So, you'll need to add the `description` to each of the values in `resources.chapters`.  If that is impractical, you could transform the data before your tests:

```js
resources.chapters.forEach(c => c.description = c.name);

given(resources.chapters).it("ConstructorAcceptsCorrectInputs", function(chapter)
{
    //...
});
```

Be aware that this is modifying the data in `resources.chapters` which may or may not affect other things.  If you don't want to modify the data, you could wrap up the data with the description like this:

```js
const testData = resources.chapters.map(c => ({
    description: c.name,
    chapter: c
}));

given(testData).it("ConstructorAcceptsCorrectInputs", function(data)
{
    const chapter = data.chapter;
    //...
});
```

**Comment by CG-Tespy** [comment]
Your solutions worked! Thank you very much ^_^
